name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          unityVersion: 2020.2.6f1

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      
      # Deploy
      # - name: Ping hook
      #   uses: fjogeleit/http-request-action@master
      #   with:
      #     url: 'https://app.buddy.works/firstbossspike/spel-ignite-web/pipelines/pipeline/318411/trigger-webhook?token=53cc0b9d465595a03cfb145718c7133f0f06743c39f859ca374deb6974d1b94609269d2116fb40072ee9c0e7f3ff77db'
      #     method: 'GET'
